# Copyright (c) 2026 Radxa Computer (Shenzhen) Co., Ltd.
# Released under the MIT license (see COPYING.MIT for the terms)

#@TYPE: Machine
#@NAME: Radxa Cubie A5E

require conf/machine/t527-demo.conf
require conf/machine/include/radxa.inc
