# Copyright (c) 2024 Radxa Computer (Shenzhen) Co., Ltd.
# Released under the MIT license (see COPYING.MIT for the terms)

#@TYPE: Machine
#@NAME: RK3528A ROCK 2F

require conf/machine/include/rk3528.inc
require conf/machine/include/radxa.inc

KERNEL_DEVICETREE = "rockchip/rk3528-rock-2f.dtb"

UBOOT_MACHINE = "rk3528_defconfig"
