require conf/machine/include/mt8195.inc
require conf/machine/include/mt7921.inc
require conf/machine/include/mt7925.inc
require conf/machine/include/radxa.inc

# Kernel
KERNEL_DEVICETREE = "mediatek/mt8395-genio-1200-radxa-nio12b-ufs.dtb"
# Shared IMX214 dual-cam overlay (CAM0 PDN GPIO54, 3V3 GPIO104)
KERNEL_DEVICETREE_OVERLAYS_AUTOLOAD = "gpu-mali.dtbo video.dtbo apusys.dtbo nio12b-camera-imx214-4lan.dtbo"

LIST_DTBO = " gpu-mali.dtbo video.dtbo apusys.dtbo"
BOOT_CONF = "\#conf-mediatek_genio-1200-radxa-nio12b-ufs.dtb\#conf-gpu-mali.dtbo\#conf-video.dtbo\#conf-apusys.dtbo"

# U-Boot
UBOOT_MACHINE = "genio_1200_radxa_nio12b_ufs_defconfig"

# libdram
LIBDRAM_BOARD_NAME = "genio-1200-evk"

# OP-TEE
OPTEE_DRAM_SIZE = "0x200000000"

# LK
LK_PROJECT = "mt8395-evk-ufs"
LK_BOARD_NAME = "${LK_PROJECT}"

# UFS storage
WIC_SECTOR_SIZE = "4096"
WIC_BLOCK_SIZE = "4096"
MACHINE_FEATURES:append = " ufs-boot ufs-system "

MACHINE_FEATURES:append = " alsa bluetooth pci usbgadget usbhost wifi tsn uc-fde"

IMAGE_INSTALL:append = " \
    rkwifibt-firmware-aic8800d80-usb \
"

MACHINEOVERRIDES =. "mt8395-evk:genio-1200-evk:mt8395-evk-ufs:genio-1200-evk-ufs:genio-1200-radxa-nio12b"
