require include/mt8195.inc
require include/mt7921.inc
require include/mt7925.inc

# Kernel
KERNEL_DEVICETREE = "mediatek/mt8395-genio-1200-radxa-nio12b-sd.dtb"
# Shared IMX214 dual-cam overlay (CAM0 PDN GPIO54, 3V3 GPIO104)
KERNEL_DEVICETREE_OVERLAYS_AUTOLOAD = "video.dtbo apusys.dtbo nio12b-camera-imx214-4lan.dtbo"

# U-Boot
UBOOT_MACHINE = "genio_1200_radxa_nio12b_sd_defconfig"

# libdram
LIBDRAM_BOARD_NAME = "genio-1200-evk"

# OP-TEE
OPTEE_DRAM_SIZE = "0x200000000"

# LK
LK_BOARD_NAME = "mt8395-demo"
# LK_BOARD_NAME = "${LK_PROJECT}"


MACHINE_FEATURES:append = " alsa bluetooth pci usbgadget usbhost wifi tsn uc-fde"

IMAGE_INSTALL:append = " \
    rkwifibt-firmware-aic8800d80-usb \
"
MACHINEOVERRIDES =. "mt8395-evk:genio-1200-evk:genio-1200-radxa-nio12b-sd"

# Remove AIOT header plugin for standard GPT (DD-compatible for SD card)
