# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "radxa"
BBFILE_PATTERN_radxa = "^${LAYERDIR}/"
BBFILE_PRIORITY_radxa = "6"

LAYERDEPENDS_radxa = "meta-scarthgap mediatek-bsp rity-bringup"
LAYERSERIES_COMPAT_radxa = "scarthgap"
